version: '3.4'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
          APP_ENV: development
    ports:
      - 3000:3000
      - 80:80
    depends_on:
      - db
    working_dir: /huh
    volumes:
      - .:/huh
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      
